"""Add pdf and tex hashes

Revision ID: 391b578f2abe
Revises: 2c633a36cf87
Create Date: 2025-07-24 02:23:12.957861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '391b578f2abe'
down_revision: Union[str, None] = '2c633a36cf87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('pdf_hash', sa.String(), nullable=True))
    op.add_column('papers', sa.Column('tex_hash', sa.String(), nullable=True))
    op.drop_index('ix_tools_name', table_name='tools')
    op.create_index(op.f('ix_tools_name'), 'tools', ['name'], unique=False)
    op.drop_column('tools', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tools_name'), table_name='tools')
    op.create_index('ix_tools_name', 'tools', ['name'], unique=True)
    op.drop_column('papers', 'tex_hash')
    op.drop_column('papers', 'pdf_hash')
    # ### end Alembic commands ###
