"""Add generation_method column

Revision ID: 70ad47f758d3
Revises: 391b578f2abe
Create Date: 2025-07-24 02:34:30.494230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ad47f758d3'
down_revision: Union[str, None] = '391b578f2abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('generation_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'generation_method')
    # ### end Alembic commands ###
