[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "echo '=== Running database migrations ===' && echo \"DATABASE_URL: ${DATABASE_URL:0:30}...\" && python -m alembic upgrade head && echo '=== Migrations complete ===' && uvicorn app.main:app --host 0.0.0.0 --port $PORT"